services:
  training:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: training-pipeout
    image: training-pipeout
    networks:
      - shared-net
    volumes:
      - ../scripts:/app/scripts
      - ../configs:/app/configs
    ports:
      - "8081:8081"
    env_file:
      - ../.env
    restart: "no"
networks:
  shared-net:
    name: ml-network
    external: true # joins the already-created network
