# -*- coding: utf-8 -*-
"""INITIAL_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztFXUA2xubQ1gGsYHi9tM2J66jQTq_tJ
"""

import pandas as pd

j = pd.read_csv("raw_ciencia_da_computacao_historico_escolar_2017_2025_1.csv")

j['Situação'].value_counts().sort_values()

i = pd.read_csv("raw_ciencia_da_computacao_inativos_2017_2025_1.csv")

# Nós temos 126 formados
# E temos 494 evadidos
# 2017 ate 2025 1

total =i["Situação atual"].value_counts().reset_index(name='Quantidade')
total



x  = i[i['Situação atual'] != 'EXCLUSAO POR CONCLUSAO (FORMADO)']

y = x["Situação atual"].value_counts().reset_index(name='Quantidade')

quantidadeEvadidos = y['Quantidade'].sum()

quantidadeEvadidos

ativos = pd.read_csv("raw_ciencia_da_computacao_ativos_2017_2025_1.csv")

ativos['Situação atual'].value_counts()

"""# Calculando Taxa de Evasão do Curso de Ciência da Computação Araguaia"""

import pandas as pd
df_ativos = pd.read_csv("discentes_ativos_anonimizados.csv")
df_inativos =  pd.read_csv("discentes_inativos_anonimizados.csv")

df_ativos = df_ativos.iloc[:-1]
df_inativos = df_inativos.iloc[:-1]

df_all  = pd.concat([df_inativos, df_ativos])

df_all2 = df_all.copy()
df_all2['PeríodoingressoAno'] = df_all2['Período ingresso'].astype(str).str[:4]

df_all2['AnoIngresso'] = pd.to_datetime(df_all2['PeríodoingressoAno'], format='%Y', errors='coerce').dt.to_period('Y')

df_all2['PeríodoingressoAno'].isnull().sum()

df_all3 = df_all2.copy()

situacoesNaoEvasao = [
    'EXCLUSAO POR CONCLUSAO (FORMADO)',
    'MATRICULADO NO PERÍODO',
    'AFASTAMENTO POR BLOQUEIO DE MATRICULA',
    'AFASTAMENTO POR TRANCAMENTO DE MATRICULA'
]



filtro_evasao = ~df_all3['Situação atual'].isin(situacoesNaoEvasao)

# 2. Aplicar a conversão e extrair o ano apenas para as linhas filtradas
df_all3.loc[filtro_evasao, 'AnoEvasao'] = pd.to_datetime(
    df_all3.loc[filtro_evasao, 'Data ocorrência'],
    format='%d/%m/%Y %H:%M:%S',
    errors='coerce'
).dt.year

df_all3['AnoEvasao'] = df_all3['AnoEvasao'].astype('Int64')
x = df_all3['AnoEvasao'].value_counts().reset_index(name='QuantidadeEvasao')
y = df_all3['PeríodoingressoAno'].value_counts().reset_index(name='QuantidadeIngresso')

y['PeríodoingressoAno'] = y['PeríodoingressoAno'].astype('Int64')

x.rename(columns={'AnoEvasao': 'Ano'}, inplace=True)
y.rename(columns={'PeríodoingressoAno': 'Ano'}, inplace=True)

mergedcsv = pd.merge(x, y, on='Ano', how='outer')

x

mergedcsv

import matplotlib.pyplot as plt
import seaborn as sns

mergedcsv_sorted = mergedcsv.sort_values(by='Ano', ascending=False)


valid_years = mergedcsv_sorted[mergedcsv_sorted['Ano'] != 0]['Ano'].unique()
last_5_years = valid_years[:5]

df_last_5_years = mergedcsv[mergedcsv['Ano'].isin(last_5_years)].sort_values(by='Ano')

df_last_5_years['QuantidadeEvasao'] = df_last_5_years['QuantidadeEvasao'].fillna(0).astype(int)
df_last_5_years['QuantidadeIngresso'] = df_last_5_years['QuantidadeIngresso'].fillna(0).astype(int)


df_last_5_years['TaxaEvasao'] = df_last_5_years.apply(lambda row: row['QuantidadeEvasao'] / row['QuantidadeIngresso'] if row['QuantidadeIngresso'] > 0 else 0, axis=1)

display(df_last_5_years)

import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.ticker import PercentFormatter

sns.set_theme(style="whitegrid")
fig = plt.figure(figsize=(10, 6))

ax = sns.barplot(
    data=df_last_5_years,
    x='Ano',
    y='TaxaEvasao',
    color='#2c7bb6'
)

for p in ax.patches:
    altura = p.get_height()
    ax.annotate(f'{altura:.1%}',
                (p.get_x() + p.get_width() / 2., altura),
                ha='center', va='bottom',
                fontsize=11, fontweight='bold', color='black',
                xytext=(0, 5), textcoords='offset points')

plt.title('Taxa de Evasão por Ano de Ingresso (Últimos 5 Anos)', fontsize=14, pad=20, fontweight='bold')
plt.xlabel('Ano de Ingresso', fontsize=12, fontweight='bold')
plt.ylabel('Taxa de Evasão (%)', fontsize=12, fontweight='bold')

ax.yaxis.set_major_formatter(PercentFormatter(1.0))

sns.despine()

plt.tight_layout()
plt.show()

display(df_last_5_years)

df_inativos.value_counts()

df_ativos['Situação atual'].value_counts()

df_inativos['Situação atual'].value_counts()

import pandas as pd
ativos = pd.read_csv("discentes_ativos_anonimizados (1).csv")

ativos['RGA_Anon'].nunique()